# Config options
markdown: rdiscount
permalink: date
exclude: [README.md]
timezone: America/Toronto
pygments: true
paginate: 5

# Site wide variables
title: Technological Ramblings
tagline: The word of Rick Eyre on topics relating to software... and other things.

# Contact Info
gh: https://github.com/RickEyre
twitter: https://twitter.com/reyre_
bitbucket: https://bitbucket.org/RichardEyre
linkedin: http://www.linkedin.com/in/eyrerichard
stackoverflow: http://stackoverflow.com/users/1214566/rick-eyre

# Disqus Info
shortname: rickeyre

# Site URL
url: http://rickeyre.ca
