# Config options
markdown: rdiscount
permalink: date
exclude: [README.md]
timezone: America/Toronto
highlighter: true
paginate: 5

# Site wide variables
title: Rick Eyre's Blog

# Contact Info
gh: https://github.com/RickEyre
twitter: https://twitter.com/reyre_
bitbucket: https://bitbucket.org/RichardEyre
linkedin: http://www.linkedin.com/in/eyrerichard
stackoverflow: http://stackoverflow.com/users/1214566/rick-eyre

# Disqus Info
shortname: rickeyre

# Site URL
url: http://rickeyre.ca
